//! Aurora-owned decoder boundaries for external immersive-audio decoders.

use std::panic::{catch_unwind, AssertUnwindSafe};

use aurora_core::{AudioBlock, AudioFormat, AudioObject, ChannelRole};
use thiserror::Error;

/// Decoded audio and object metadata for one decoder output frame.
#[derive(Debug, Clone, PartialEq)]
pub struct DecodedFrame {
    /// Decoded PCM samples.
    pub audio: AudioBlock,
    /// Object metadata associated with the decoded block.
    pub objects: Vec<AudioObject>,
}

/// Semantic class an adapter promises to expose to Aurora.
///
/// These modes are intentionally not interchangeable. In particular, a channel-bed decoder or
/// synthetic upmixer must never be presented as a native object-scene decoder when an immersive
/// source was requested.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecoderOutputSemantics {
    /// Native channel PCM/bed decode with no real object-scene metadata.
    ChannelPcm,
    /// Native decoded PCM accompanied by real object-scene metadata from the source/backend.
    ObjectScene,
    /// PCM generated by a synthetic upmix. This is explicitly weaker than native object decode.
    SyntheticUpmix,
}

/// Decoder metadata reported by an adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecoderInfo {
    /// Human-readable adapter name.
    pub name: &'static str,
    /// Whether this adapter is intended for production use.
    pub production_ready: bool,
    /// Short maturity label such as `experimental` or `preferred-open`.
    pub maturity: &'static str,
    /// Semantic class this adapter promises to expose.
    pub output_semantics: DecoderOutputSemantics,
}

/// Errors returned by decoder adapters.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DecoderError {
    /// Adapter feature is disabled or unavailable.
    #[error("decoder adapter is unavailable: {0}")]
    Unavailable(&'static str),
    /// Input format is unsupported by this adapter.
    #[error("unsupported decoder input: {0}")]
    UnsupportedInput(&'static str),
    /// External decoder process failed.
    #[error("external decoder process failed: {0}")]
    ExternalProcess(String),
    /// An in-process decoder backend panicked and was isolated at the adapter boundary.
    #[error("decoder backend panicked during {0}; explicit adapter recovery is required")]
    BackendPanic(&'static str),
    /// A panic-isolated decoder remains latched faulted until explicit adapter recovery.
    #[error("decoder backend is latched faulted after a panic; explicit adapter recovery is required")]
    BackendFaulted,
}

/// Offline/chunk decoder boundary retained for file and preparation paths.
pub trait Decoder {
    /// Returns static adapter metadata including the semantic strength of its output.
    fn info(&self) -> DecoderInfo;

    /// Configures decoder output format.
    fn configure(&mut self, output_format: AudioFormat) -> Result<(), DecoderError>;

    /// Decodes one offline input chunk.
    fn decode_chunk(&mut self, input: &[u8]) -> Result<Option<DecodedFrame>, DecoderError>;

    /// Clears decoder state.
    fn reset(&mut self);
}

/// Transport presented to a live decoder backend.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecoderPacketTransport {
    /// Raw codec elementary bytes.
    RawElementary,
    /// Payload originated from an IEC61937 burst and retains its data-type code.
    Iec61937,
}

/// Borrowed packet supplied by a live ingress adapter.
///
/// Aurora deliberately keeps this contract independent of ALSA, USB, eARC, HDMI, a particular
/// host processor, or a particular decoder implementation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecoderPacket<'a> {
    /// Packet transport semantics.
    pub transport: DecoderPacketTransport,
    /// IEC61937 data-type code when known, for example `0x15` for E-AC-3.
    pub data_type: Option<u8>,
    /// Codec payload bytes. For IEC61937 this is the extracted payload, not padding.
    pub payload: &'a [u8],
    /// True when the packet starts a new stream epoch after a gap, seek, relock, or format change.
    pub discontinuity: bool,
}

/// Live decoder output configuration independent of final speaker count.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StreamingDecoderConfig {
    /// PCM sample rate Aurora expects after decode/resampling.
    pub sample_rate: u32,
    /// Preferred media processing block size.
    pub block_size: usize,
    /// Hard upper bound on decoded PCM channels.
    pub maximum_pcm_channels: usize,
}

/// Semantic role of one decoded PCM channel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecodedChannelKind {
    /// Fixed bed channel with an explicit Aurora role.
    Bed(ChannelRole),
    /// Dynamic-object PCM. Object identity is supplied by [`ObjectChannelBinding`].
    Object,
    /// Decoder could not map the channel to a safe semantic role.
    Unknown,
}

/// Complete object-to-PCM-channel binding for one active object.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjectChannelBinding {
    /// Stable object identifier matching [`AudioObject::id`].
    pub object_id: String,
    /// Zero-based decoded PCM channel index carrying this object's audio.
    pub channel_index: usize,
}

/// Streaming frame preserving source PCM semantics required for actual object mixing.
#[derive(Debug, Clone, PartialEq)]
pub struct StreamingDecodedFrame {
    /// Decoded PCM and current object metadata.
    pub decoded: DecodedFrame,
    /// One semantic entry for every decoded PCM channel.
    pub channel_kinds: Vec<DecodedChannelKind>,
    /// Complete active object-to-channel table for this frame.
    ///
    /// Adapters whose upstream ABI sends sparse binding updates must cache them and expose the
    /// complete active table here so Aurora never guesses stale object/channel associations.
    pub object_channels: Vec<ObjectChannelBinding>,
}

/// Frames emitted after one streaming decoder packet.
#[derive(Debug, Clone, PartialEq)]
pub struct DecodedBatch {
    /// Zero or more decoded frames. A decoder may buffer before emitting the first frame.
    pub frames: Vec<StreamingDecodedFrame>,
    /// Backend assertion that native source object metadata is present for this batch/stream.
    /// This must never be set for synthetic upmix metadata.
    pub native_objects_present: bool,
}

impl DecodedBatch {
    /// Creates an empty buffering result.
    pub fn empty() -> Self {
        Self {
            frames: Vec::new(),
            native_objects_present: false,
        }
    }
}

/// Stateful live-decoder boundary used by the encoded ingress runtime.
///
/// Implementations may wrap an in-process library, a reviewed ABI bridge, or an out-of-process
/// decoder. They must not silently substitute channel PCM or synthetic upmix metadata for a
/// requested native object scene.
pub trait StreamingDecoder {
    /// Returns static adapter metadata including semantic strength.
    fn info(&self) -> DecoderInfo;

    /// Configures live output expectations before packets are accepted.
    fn configure_stream(&mut self, config: StreamingDecoderConfig) -> Result<(), DecoderError>;

    /// Pushes one bounded packet and returns any decoded frames made available by it.
    fn push_packet(&mut self, packet: DecoderPacket<'_>) -> Result<DecodedBatch, DecoderError>;

    /// Clears stream history after a discontinuity or explicit recovery.
    fn reset_stream(&mut self);
}

/// Panic-isolating adapter for in-process streaming decoder backends.
///
/// This wrapper belongs on the media/control side, not inside Aurora's hard realtime callback.
/// Once a backend panic is observed, packet/configuration calls fail closed until [`Self::recover`]
/// successfully resets the backend. Ordinary `reset_stream` calls intentionally do not clear a
/// panic latch, so a discontinuity cannot accidentally turn a crashed backend audible again.
pub struct PanicIsolatedStreamingDecoder<D> {
    inner: D,
    info: DecoderInfo,
    faulted: bool,
}

impl<D> PanicIsolatedStreamingDecoder<D>
where
    D: StreamingDecoder,
{
    /// Wraps a backend after safely caching its static metadata.
    pub fn try_new(inner: D) -> Result<Self, DecoderError> {
        let info = catch_unwind(AssertUnwindSafe(|| inner.info()))
            .map_err(|_| DecoderError::BackendPanic("info"))?;
        Ok(Self {
            inner,
            info,
            faulted: false,
        })
    }

    /// Returns whether a backend panic is currently latched.
    pub fn is_faulted(&self) -> bool {
        self.faulted
    }

    /// Explicitly attempts to reset and re-arm a backend after a panic.
    pub fn recover(&mut self) -> Result<(), DecoderError> {
        match catch_unwind(AssertUnwindSafe(|| self.inner.reset_stream())) {
            Ok(()) => {
                self.faulted = false;
                Ok(())
            }
            Err(_) => {
                self.faulted = true;
                Err(DecoderError::BackendPanic("recovery reset"))
            }
        }
    }

    /// Borrows the wrapped backend for diagnostics on non-realtime control paths.
    pub fn inner(&self) -> &D {
        &self.inner
    }
}

impl<D> StreamingDecoder for PanicIsolatedStreamingDecoder<D>
where
    D: StreamingDecoder,
{
    fn info(&self) -> DecoderInfo {
        self.info.clone()
    }

    fn configure_stream(&mut self, config: StreamingDecoderConfig) -> Result<(), DecoderError> {
        if self.faulted {
            return Err(DecoderError::BackendFaulted);
        }
        match catch_unwind(AssertUnwindSafe(|| self.inner.configure_stream(config))) {
            Ok(result) => result,
            Err(_) => {
                self.faulted = true;
                Err(DecoderError::BackendPanic("configure_stream"))
            }
        }
    }

    fn push_packet(&mut self, packet: DecoderPacket<'_>) -> Result<DecodedBatch, DecoderError> {
        if self.faulted {
            return Err(DecoderError::BackendFaulted);
        }
        match catch_unwind(AssertUnwindSafe(|| self.inner.push_packet(packet))) {
            Ok(result) => result,
            Err(_) => {
                self.faulted = true;
                Err(DecoderError::BackendPanic("push_packet"))
            }
        }
    }

    fn reset_stream(&mut self) {
        if self.faulted {
            return;
        }
        if catch_unwind(AssertUnwindSafe(|| self.inner.reset_stream())).is_err() {
            self.faulted = true;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug)]
    struct PanicDecoder {
        panic_on_push: bool,
        panic_on_reset: bool,
    }

    impl StreamingDecoder for PanicDecoder {
        fn info(&self) -> DecoderInfo {
            DecoderInfo {
                name: "panic-decoder",
                production_ready: false,
                maturity: "test",
                output_semantics: DecoderOutputSemantics::ObjectScene,
            }
        }

        fn configure_stream(&mut self, _config: StreamingDecoderConfig) -> Result<(), DecoderError> {
            Ok(())
        }

        fn push_packet(&mut self, _packet: DecoderPacket<'_>) -> Result<DecodedBatch, DecoderError> {
            if self.panic_on_push {
                panic!("intentional decoder panic");
            }
            Ok(DecodedBatch::empty())
        }

        fn reset_stream(&mut self) {
            if self.panic_on_reset {
                panic!("intentional reset panic");
            }
            self.panic_on_push = false;
        }
    }

    fn packet() -> DecoderPacket<'static> {
        DecoderPacket {
            transport: DecoderPacketTransport::Iec61937,
            data_type: Some(0x15),
            payload: &[1, 2, 3],
            discontinuity: false,
        }
    }

    #[test]
    fn panic_isolation_latches_until_explicit_recovery() {
        let backend = PanicDecoder {
            panic_on_push: true,
            panic_on_reset: false,
        };
        let mut decoder = PanicIsolatedStreamingDecoder::try_new(backend).unwrap();
        assert_eq!(
            decoder.push_packet(packet()),
            Err(DecoderError::BackendPanic("push_packet"))
        );
        assert!(decoder.is_faulted());
        decoder.reset_stream();
        assert!(decoder.is_faulted());
        assert_eq!(decoder.push_packet(packet()), Err(DecoderError::BackendFaulted));
        decoder.recover().unwrap();
        assert!(!decoder.is_faulted());
        assert_eq!(decoder.push_packet(packet()), Ok(DecodedBatch::empty()));
    }

    #[test]
    fn failed_recovery_keeps_backend_latched() {
        let backend = PanicDecoder {
            panic_on_push: true,
            panic_on_reset: true,
        };
        let mut decoder = PanicIsolatedStreamingDecoder::try_new(backend).unwrap();
        assert_eq!(
            decoder.push_packet(packet()),
            Err(DecoderError::BackendPanic("push_packet"))
        );
        assert_eq!(
            decoder.recover(),
            Err(DecoderError::BackendPanic("recovery reset"))
        );
        assert!(decoder.is_faulted());
        assert_eq!(decoder.push_packet(packet()), Err(DecoderError::BackendFaulted));
    }
}
