//! Aurora-owned decoder boundaries for external immersive-audio decoders.

use aurora_core::{AudioBlock, AudioFormat, AudioObject, ChannelRole};
use thiserror::Error;

/// Decoded audio and object metadata for one decoder output frame.
#[derive(Debug, Clone, PartialEq)]
pub struct DecodedFrame {
    /// Decoded PCM samples.
    pub audio: AudioBlock,
    /// Object metadata associated with the decoded block.
    pub objects: Vec<AudioObject>,
}

/// Semantic class an adapter promises to expose to Aurora.
///
/// These modes are intentionally not interchangeable. In particular, a channel-bed decoder or
/// synthetic upmixer must never be presented as a native object-scene decoder when an immersive
/// source was requested.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecoderOutputSemantics {
    /// Native channel PCM/bed decode with no real object-scene metadata.
    ChannelPcm,
    /// Native decoded PCM accompanied by real object-scene metadata from the source/backend.
    ObjectScene,
    /// PCM generated by a synthetic upmix. This is explicitly weaker than native object decode.
    SyntheticUpmix,
}

/// Decoder metadata reported by an adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecoderInfo {
    /// Human-readable adapter name.
    pub name: &'static str,
    /// Whether this adapter is intended for production use.
    pub production_ready: bool,
    /// Short maturity label such as `experimental` or `preferred-open`.
    pub maturity: &'static str,
    /// Semantic class this adapter promises to expose.
    pub output_semantics: DecoderOutputSemantics,
}

/// Errors returned by decoder adapters.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DecoderError {
    /// Adapter feature is disabled or unavailable.
    #[error("decoder adapter is unavailable: {0}")]
    Unavailable(&'static str),
    /// Input format is unsupported by this adapter.
    #[error("unsupported decoder input: {0}")]
    UnsupportedInput(&'static str),
    /// External decoder process failed.
    #[error("external decoder process failed: {0}")]
    ExternalProcess(String),
}

/// Offline/chunk decoder boundary retained for file and preparation paths.
pub trait Decoder {
    /// Returns static adapter metadata including the semantic strength of its output.
    fn info(&self) -> DecoderInfo;

    /// Configures decoder output format.
    fn configure(&mut self, output_format: AudioFormat) -> Result<(), DecoderError>;

    /// Decodes one offline input chunk.
    fn decode_chunk(&mut self, input: &[u8]) -> Result<Option<DecodedFrame>, DecoderError>;

    /// Clears decoder state.
    fn reset(&mut self);
}

/// Transport presented to a live decoder backend.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecoderPacketTransport {
    /// Raw codec elementary bytes.
    RawElementary,
    /// Payload originated from an IEC61937 burst and retains its data-type code.
    Iec61937,
}

/// Borrowed packet supplied by a live ingress adapter.
///
/// Aurora deliberately keeps this contract independent of ALSA, USB, eARC, HDMI, a particular
/// host processor, or a particular decoder implementation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecoderPacket<'a> {
    /// Packet transport semantics.
    pub transport: DecoderPacketTransport,
    /// IEC61937 data-type code when known, for example `0x15` for E-AC-3.
    pub data_type: Option<u8>,
    /// Codec payload bytes. For IEC61937 this is the extracted payload, not padding.
    pub payload: &'a [u8],
    /// True when the packet starts a new stream epoch after a gap, seek, relock, or format change.
    pub discontinuity: bool,
}

/// Live decoder output configuration independent of final speaker count.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StreamingDecoderConfig {
    /// PCM sample rate Aurora expects after decode/resampling.
    pub sample_rate: u32,
    /// Preferred media processing block size.
    pub block_size: usize,
    /// Hard upper bound on decoded PCM channels.
    pub maximum_pcm_channels: usize,
}

/// Semantic role of one decoded PCM channel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecodedChannelKind {
    /// Fixed bed channel with an explicit Aurora role.
    Bed(ChannelRole),
    /// Dynamic-object PCM. Object identity is supplied by [`ObjectChannelBinding`].
    Object,
    /// Decoder could not map the channel to a safe semantic role.
    Unknown,
}

/// Complete object-to-PCM-channel binding for one active object.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjectChannelBinding {
    /// Stable object identifier matching [`AudioObject::id`].
    pub object_id: String,
    /// Zero-based decoded PCM channel index carrying this object's audio.
    pub channel_index: usize,
}

/// Streaming frame preserving source PCM semantics required for actual object mixing.
#[derive(Debug, Clone, PartialEq)]
pub struct StreamingDecodedFrame {
    /// Decoded PCM and current object metadata.
    pub decoded: DecodedFrame,
    /// One semantic entry for every decoded PCM channel.
    pub channel_kinds: Vec<DecodedChannelKind>,
    /// Complete active object-to-channel table for this frame.
    ///
    /// Adapters whose upstream ABI sends sparse binding updates must cache them and expose the
    /// complete active table here so Aurora never guesses stale object/channel associations.
    pub object_channels: Vec<ObjectChannelBinding>,
}

/// Frames emitted after one streaming decoder packet.
#[derive(Debug, Clone, PartialEq)]
pub struct DecodedBatch {
    /// Zero or more decoded frames. A decoder may buffer before emitting the first frame.
    pub frames: Vec<StreamingDecodedFrame>,
    /// Backend assertion that native source object metadata is present for this batch/stream.
    /// This must never be set for synthetic upmix metadata.
    pub native_objects_present: bool,
}

impl DecodedBatch {
    /// Creates an empty buffering result.
    pub fn empty() -> Self {
        Self {
            frames: Vec::new(),
            native_objects_present: false,
        }
    }
}

/// Stateful live-decoder boundary used by the encoded ingress runtime.
///
/// Implementations may wrap an in-process library, a reviewed ABI bridge, or an out-of-process
/// decoder. They must not silently substitute channel PCM or synthetic upmix metadata for a
/// requested native object scene.
pub trait StreamingDecoder {
    /// Returns static adapter metadata including semantic strength.
    fn info(&self) -> DecoderInfo;

    /// Configures live output expectations before packets are accepted.
    fn configure_stream(&mut self, config: StreamingDecoderConfig) -> Result<(), DecoderError>;

    /// Pushes one bounded packet and returns any decoded frames made available by it.
    fn push_packet(&mut self, packet: DecoderPacket<'_>) -> Result<DecodedBatch, DecoderError>;

    /// Clears stream history after a discontinuity or explicit recovery.
    fn reset_stream(&mut self);
}
