[package]
name = "aurora-layout-playback-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-decoder-api = { path = "../aurora-decoder-api" }
aurora-decoder-engine = { path = "../aurora-decoder-engine" }
aurora-decoder-open = { path = "../aurora-decoder-open" }
aurora-dsp-basic = { path = "../aurora-dsp-basic" }
aurora-encoded-input = { path = "../aurora-encoded-input" }
aurora-encoded-runtime = { path = "../aurora-encoded-runtime" }
aurora-speaker-output = { path = "../aurora-speaker-output" }
thiserror.workspace = true

[dev-dependencies]
aurora-alsa-output = { path = "../aurora-alsa-output" }
aurora-iec61937 = { path = "../aurora-iec61937" }
