[package]
name = "aurora-decoder-open"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"
publish = false

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-decoder-api = { path = "../aurora-decoder-api" }
oxideav-ac3 = "0.0.11"
oxideav-core = "0.1"
thiserror = { workspace = true }
