[package]
name = "aurora-decoder-open"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
publish = false

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-decoder-api = { path = "../aurora-decoder-api" }
openjoc-api = { git = "https://github.com/chyinan/OpenJOC", rev = "e7e03bc834ac0483770933cdc50ac058b100d1e2", package = "openjoc-api" }
openjoc-eac3 = { git = "https://github.com/chyinan/OpenJOC", rev = "e7e03bc834ac0483770933cdc50ac058b100d1e2", package = "openjoc-eac3" }
openjoc-ffmpeg = { git = "https://github.com/chyinan/OpenJOC", rev = "e7e03bc834ac0483770933cdc50ac058b100d1e2", package = "openjoc-ffmpeg", default-features = false }
oxideav-ac3 = "0.0.11"
oxideav-core = "0.1"
thiserror = { workspace = true }

[dev-dependencies]
aurora-alsa-output = { path = "../aurora-alsa-output" }
aurora-dsp-basic = { path = "../aurora-dsp-basic" }
openjoc-scene = { git = "https://github.com/chyinan/OpenJOC", rev = "e7e03bc834ac0483770933cdc50ac058b100d1e2", package = "openjoc-scene" }
