[package]
name = "aurora-decoder-open"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
publish = false

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-decoder-api = { path = "../aurora-decoder-api" }
openjoc-api = { git = "https://github.com/chyinan/OpenJOC", rev = "77e842303d4cb9d95b29ff41a3b9ed230f246b80", package = "openjoc-api" }
openjoc-eac3 = { git = "https://github.com/chyinan/OpenJOC", rev = "77e842303d4cb9d95b29ff41a3b9ed230f246b80", package = "openjoc-eac3" }
oxideav-ac3 = "0.0.11"
oxideav-core = "0.1"
thiserror = { workspace = true }
