//! Structured inspection-owned error contracts.

use core::fmt;

/// A published inspection projection limit.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InspectionLimit {
    /// Maximum retained findings.
    Findings,
    /// Maximum bytes in one copied source string.
    StringBytes,
    /// Maximum bytes across copied source strings.
    TotalStringBytes,
    /// Maximum identities in either channel direction.
    Channels,
    /// Maximum routes.
    Routes,
    /// Maximum speakers.
    Speakers,
    /// Maximum setup stages.
    SetupStages,
    /// Maximum setup dependencies.
    SetupDependencies,
}

/// Deterministic inspection output format.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InspectionOutputFormat {
    /// Compact canonical JSON.
    Json,
    /// Stable human-readable text.
    Text,
}

/// A finite floating-point field validated before formatting.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InspectionFloatField {
    /// Optional normalized horizontal renderer spread.
    HorizontalSpread,
    /// Normalized speaker x direction.
    SpeakerNormalizedX,
    /// Normalized speaker y direction.
    SpeakerNormalizedY,
    /// Normalized speaker z direction.
    SpeakerNormalizedZ,
}

/// A relationship that must agree between paired prepared plans.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PlanRelationship {
    /// Runtime and setup device intent must agree.
    DeviceIntent,
    /// Runtime and setup requested formats must agree.
    RequestedAudioFormat,
    /// Runtime and setup renderer intent must agree.
    RendererIntent,
    /// Runtime and setup topology intent must agree.
    TopologyIntent,
    /// Runtime and setup DSP intent must agree.
    DspIntent,
}

/// Structured failures produced while projecting prepared plans.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum InspectionError {
    /// A published finite projection bound was exceeded.
    LimitExceeded {
        /// Limit that was exceeded.
        limit: InspectionLimit,
        /// Actual source value.
        actual: usize,
        /// Published maximum.
        maximum: usize,
    },
    /// The supplied setup plan was not derived from the supplied runtime facts.
    SourcePlansMismatch {
        /// Relationship that differs.
        relationship: PlanRelationship,
    },
    /// Checked cumulative string accounting overflowed.
    StringAccountingOverflow,
    /// Checked serialized collection-entry accounting overflowed.
    SerializedCollectionAccountingOverflow,
    /// The report contains more serialized collection entries than allowed.
    SerializedCollectionEntriesExceeded {
        /// Actual total collection entries.
        actual: usize,
        /// Published maximum.
        maximum: usize,
    },
    /// The fixed schema nesting depth exceeds the formatter limit.
    NestingDepthExceeded {
        /// Actual schema nesting depth.
        actual: usize,
        /// Published maximum.
        maximum: usize,
    },
    /// A finite floating-point invariant was violated.
    NonFiniteFloat {
        /// Field containing the non-finite value.
        field: InspectionFloatField,
    },
    /// A formatter produced more bytes than its published output bound.
    SerializedOutputTooLarge {
        /// Output format whose bound was exceeded.
        format: InspectionOutputFormat,
        /// Actual generated bytes.
        actual: usize,
        /// Published maximum.
        maximum: usize,
    },
    /// Inspection-owned JSON serialization failed after validation.
    JsonSerializationFailed,
}

impl fmt::Display for InspectionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LimitExceeded {
                limit,
                actual,
                maximum,
            } => write!(
                formatter,
                "inspection limit {limit:?} exceeded: {actual} > {maximum}"
            ),
            Self::SourcePlansMismatch { relationship } => {
                write!(formatter, "prepared plans disagree on {relationship:?}")
            }
            Self::StringAccountingOverflow => {
                formatter.write_str("inspection string accounting overflowed")
            }
            Self::SerializedCollectionAccountingOverflow => {
                formatter.write_str("inspection collection accounting overflowed")
            }
            Self::SerializedCollectionEntriesExceeded { actual, maximum } => write!(
                formatter,
                "serialized collection entries exceeded: {actual} > {maximum}"
            ),
            Self::NestingDepthExceeded { actual, maximum } => {
                write!(
                    formatter,
                    "inspection nesting depth exceeded: {actual} > {maximum}"
                )
            }
            Self::NonFiniteFloat { field } => {
                write!(formatter, "inspection float is non-finite: {field:?}")
            }
            Self::SerializedOutputTooLarge {
                format,
                actual,
                maximum,
            } => write!(
                formatter,
                "{format:?} inspection output too large: {actual} > {maximum} bytes"
            ),
            Self::JsonSerializationFailed => {
                formatter.write_str("inspection-owned JSON serialization failed")
            }
        }
    }
}

impl std::error::Error for InspectionError {}
