[package]
name = "aurora-renderer-libspatialaudio"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ammarxz9333-cell/Auroraaudio"
rust-version = "1.78"

[workspace]

[dependencies]
aurora-core = { path = "../../crates/aurora-core" }
aurora-renderer-api = { path = "../../crates/aurora-renderer-api" }

[dev-dependencies]
aurora-renderer-vbap = { path = "../../crates/aurora-renderer-vbap" }
aurora-test-alloc = { path = "../../crates/aurora-test-alloc" }
