[package]
name = "aurora-decoder-engine"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license-file = "LICENSE"
publish = false

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-decoder-api = { path = "../aurora-decoder-api" }
aurora-decoder-open = { path = "../aurora-decoder-open" }
oxideav-ac4 = "0.0.8"
oxideav-core = "0.1"
thiserror = { workspace = true }
