[package]
name = "aurora-network-genavb-runtime"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
aurora-network-esp-avb = { path = "../aurora-network-esp-avb" }
aurora-network-genavb = { path = "../aurora-network-genavb" }
aurora-network-genavb-avdecc = { path = "../aurora-network-genavb-avdecc" }
aurora-network-genavb-session = { path = "../aurora-network-genavb-session" }
aurora-realtime-audio-api = { path = "../../crates/aurora-realtime-audio-api" }

[lib]
path = "src/lib.rs"

[workspace]
