[package]
name = "aurora-runtime-materialization"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aurora-dsp-basic = { path = "../aurora-dsp-basic" }
aurora-realtime-engine = { path = "../aurora-realtime-engine" }
aurora-scene = { path = "../aurora-scene" }
