[package]
name = "aurora-runtime-materialization"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aurora-dsp-basic = { path = "../aurora-dsp-basic" }
aurora-realtime-engine = { path = "../aurora-realtime-engine" }
aurora-renderer-api = { path = "../aurora-renderer-api" }
aurora-renderer-basic = { path = "../aurora-renderer-basic" }
aurora-renderer-vbap = { path = "../aurora-renderer-vbap" }
aurora-runtime-assembly = { path = "../aurora-runtime-assembly" }
aurora-scene = { path = "../aurora-scene" }

[dev-dependencies]
aurora-core = { path = "../aurora-core" }
aurora-dsp-api = { path = "../aurora-dsp-api" }
serde_json.workspace = true
